apiVersion: v1
kind: Service
metadata:
  name: private-node
  namespace: {{ .Release.Namespace }}
  labels:
    app: private-node
spec:
  ports:
  - port: 9933
    name: rpc
  - port: 9615
    name: metrics
  selector:
    app: private-node
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: private-node-p2p
  namespace: {{ .Release.Namespace }}
  labels:
    app: private-node
spec:
  ports:
  - port: {{ .Values.p2p_port }}
    targetPort: 30333
    protocol: TCP
    name: dot-p2p-port
  loadBalancerIP: {{ .Values.p2p_ip }}
  selector:
    app: private-node
  type: LoadBalancer
